/* Shared mock data for Security Repo Watch variants */

const CHECK_OPTS = [
  { id: "secrets", label: "Secrets", hint: "Scan the PR diff for leaked credentials and API keys." },
  { id: "sast", label: "SAST", hint: "Static analysis for insecure patterns in changed files." },
  { id: "iac", label: "IaC", hint: "Terraform / K8s / CloudFormation misconfigurations." },
  { id: "sbom", label: "SBOM", hint: "Dependency inventory for this PR’s lockfiles." },
  { id: "ai_review", label: "OPA Review (AI)", hint: "Enqueue Bugbot AI review when this repo is watched." },
];

const CONNECTORS = [
  { id: "gh-app-acme", label: "GitHub App · acme-prod (install 88421)", live: true },
  { id: "gh-pat-ops", label: "PAT · ops-readonly", live: false },
];

const AVAILABLE = [
  { full_name: "acme/checkout-api", private: true },
  { full_name: "acme/opa-agent", private: true },
  { full_name: "acme/billing-worker", private: true },
  { full_name: "acme/edge-gateway", private: false },
  { full_name: "acme/design-system", private: true },
  { full_name: "acme/docs-site", private: false },
  { full_name: "acme-platform/infra", private: true },
  { full_name: "acme-platform/ci-templates", private: false },
];

const WATCHED_SEED = [
  {
    repo: "acme/checkout-api",
    service: "checkout-api",
    enabled: true,
    aiBlocking: true,
    autoReviewer: true,
    minScore: 72,
    checks: ["secrets", "sast", "iac", "ai_review"],
    jobs24h: 6,
    lastJob: "9m ago",
    openPrs: [
      { n: 412, title: "Tighten webhook HMAC", draft: false },
      { n: 418, title: "Rate-limit checkout retries", draft: false },
    ],
  },
  {
    repo: "acme/opa-agent",
    service: "opa-agent",
    enabled: true,
    aiBlocking: true,
    autoReviewer: false,
    minScore: 80,
    checks: ["secrets", "sast", "ai_review"],
    jobs24h: 4,
    lastJob: "22m ago",
    openPrs: [{ n: 91, title: "IAST probe sampling", draft: false }],
  },
  {
    repo: "acme/billing-worker",
    service: "billing",
    enabled: true,
    aiBlocking: false,
    autoReviewer: true,
    minScore: 0,
    checks: ["secrets", "sbom", "ai_review"],
    jobs24h: 2,
    lastJob: "1h ago",
    openPrs: [{ n: 55, title: "Idempotent invoice replay", draft: true }],
  },
  {
    repo: "acme/edge-gateway",
    service: "edge",
    enabled: false,
    aiBlocking: false,
    autoReviewer: false,
    minScore: 60,
    checks: ["secrets", "sast"],
    jobs24h: 0,
    lastJob: "3d ago",
    openPrs: [],
  },
  {
    repo: "acme/design-system",
    service: "design-system",
    enabled: true,
    aiBlocking: true,
    autoReviewer: true,
    minScore: 65,
    checks: ["secrets", "sast", "ai_review"],
    jobs24h: 3,
    lastJob: "41m ago",
    openPrs: [{ n: 220, title: "Token contrast audit", draft: false }],
  },
  {
    repo: "acme-platform/infra",
    service: "infra",
    enabled: true,
    aiBlocking: true,
    autoReviewer: false,
    minScore: 85,
    checks: ["secrets", "iac", "sbom", "ai_review"],
    jobs24h: 5,
    lastJob: "14m ago",
    openPrs: [
      { n: 88, title: "Restrict SG egress", draft: false },
      { n: 90, title: "KMS key rotation", draft: false },
    ],
  },
];

const CONTEXTS_SEED = [
  {
    id: "ctx-1",
    repo: "acme/checkout-api",
    title: "Auth & trust boundaries",
    source: "manual",
    tags: ["security"],
    group: "grp-checkout",
  },
  {
    id: "ctx-2",
    repo: "acme/design-system",
    title: "Design-system enforcement",
    source: "ai",
    tags: ["design", "ui"],
    group: "grp-ui",
  },
  {
    id: "ctx-3",
    repo: "acme-platform/infra",
    title: "Network & KMS invariants",
    source: "manual",
    tags: ["ops"],
    group: "grp-infra",
  },
];

const AI_STATUS = {
  keySet: true,
  scope: "user",
  model: "auto",
  user: "nmeloni",
  org: "acme-prod",
};

const JOBS_SEED = [
  {
    id: "scmjob-8f2a1c",
    repo: "acme/checkout-api",
    pr: 412,
    sha: "a3f91c2",
    title: "fix: tenant-scoped cart mutate",
    author: "alice@acme",
    status: "waiting",
    result: "approval held",
    tone: "warn",
    age: "9m",
    risk: 42,
    honesty: "Watched repo, checks enabled. New SHA cancelled superseded job scmjob-44be90.",
    children: [
      { step: "prepare", status: "completed", detail: "worktree @ a3f91c2" },
      { step: "security", status: "completed", detail: "gate pass · min high" },
      { step: "bugbot", status: "completed", detail: "2 findings · max medium" },
      { step: "approval", status: "waiting", detail: "risk 42 · needs human" },
      { step: "cloud", status: "skipped", detail: "prefs: cloud off" },
    ],
    findings: [
      { sev: "medium", rule: "authz-missing-tenant", where: "src/cart/checkout.ts:118" },
      { sev: "low", rule: "trust-boundary-log", where: "src/cart/totals.ts:44" },
    ],
    verdict: "Gate passed. Bugbot found 2 issues. Approval waiting — risk 42.",
  },
  {
    id: "scmjob-b2f881",
    repo: "acme/billing-worker",
    pr: 304,
    sha: "e91c220",
    title: "fix: invoice PDF path traversal",
    author: "devon@acme",
    status: "running",
    result: "bugbot in progress",
    tone: "warn",
    age: "3h",
    risk: null,
    honesty: "Watched. AI blocking on.",
    children: [
      { step: "prepare", status: "completed", detail: "worktree ready" },
      { step: "security", status: "completed", detail: "gate pass" },
      { step: "bugbot", status: "running", detail: "analyzing 14 files…" },
      { step: "approval", status: "queued", detail: "waiting on bugbot" },
    ],
    findings: [
      { sev: "high", rule: "path-traversal", where: "internal/pdf/render.go:88" },
    ],
    verdict: "In flight — security green; AI still running.",
  },
  {
    id: "scmjob-c0a991",
    repo: "acme-platform/infra",
    pr: 88,
    sha: "11ab9c0",
    title: "Restrict SG egress",
    author: "ops@acme",
    status: "queued",
    result: "stack waiting",
    tone: "info",
    age: "2m",
    risk: null,
    honesty: "Queued behind checkout-api#412 in the same review stack.",
    children: [
      { step: "prepare", status: "queued", detail: "stack concurrency" },
    ],
    findings: [],
    verdict: "Waiting for stack drain (serial concurrency).",
  },
  {
    id: "scmjob-1c90de",
    repo: "acme/opa-agent",
    pr: 91,
    sha: "b81ee04",
    title: "IAST probe sampling",
    author: "nmeloni",
    status: "completed",
    result: "gate pass · ai clean",
    tone: "ok",
    age: "2h",
    risk: 8,
    honesty: "First run for this PR.",
    children: [
      { step: "prepare", status: "completed", detail: "ok" },
      { step: "security", status: "completed", detail: "gate pass" },
      { step: "bugbot", status: "completed", detail: "0 findings" },
      { step: "approval", status: "completed", detail: "auto · score 91" },
    ],
    findings: [],
    verdict: "Clean. Gate and AI completed with no findings.",
  },
  {
    id: "scmjob-c71ef3",
    repo: "acme/checkout-api",
    pr: 409,
    sha: "90ab11e",
    title: "chore: bump cart SDK",
    author: "ci-bot@acme",
    status: "failed",
    result: "AI timeout",
    tone: "error",
    age: "52m",
    risk: 0,
    honesty: "Watched. AI child timed out after 600s.",
    children: [
      { step: "prepare", status: "completed", detail: "ok" },
      { step: "security", status: "completed", detail: "gate pass" },
      { step: "bugbot", status: "failed", detail: "timeout 600s" },
    ],
    findings: [],
    verdict: "Gate OK. Bugbot failed — retry or re-run OPA Review.",
  },
  {
    id: "scmjob-33ac10",
    repo: "acme/design-system",
    pr: 220,
    sha: "c0ffee1",
    title: "Token contrast audit",
    author: "sam@acme",
    status: "completed",
    result: "ai blocked merge",
    tone: "error",
    age: "5h",
    risk: 78,
    honesty: "AI blocking on · design context packed.",
    children: [
      { step: "prepare", status: "completed", detail: "ok" },
      { step: "security", status: "completed", detail: "gate fail · critical" },
      { step: "bugbot", status: "completed", detail: "1 critical" },
      { step: "approval", status: "blocked", detail: "score 22" },
    ],
    findings: [
      { sev: "critical", rule: "contrast-fail", where: "tokens/color.css:12" },
    ],
    verdict: "Blocked. Critical contrast regression on primary button.",
  },
  {
    id: "scmjob-44be90",
    repo: "acme/checkout-api",
    pr: 412,
    sha: "99old01",
    title: "fix: tenant-scoped cart mutate",
    author: "alice@acme",
    status: "cancelled",
    result: "superseded",
    tone: "",
    age: "14m",
    risk: null,
    honesty: "Superseded by scmjob-8f2a1c on newer SHA.",
    children: [],
    findings: [],
    verdict: "Cancelled when a newer synchronize arrived.",
  },
  {
    id: "scmjob-skip01",
    repo: "acme/docs-site",
    pr: 12,
    sha: "d0c5001",
    title: "docs: changelog",
    author: "maya@acme",
    status: "skipped",
    result: "not watched",
    tone: "info",
    age: "1d",
    risk: null,
    honesty: "Installed but not in Dashboard watch set — receipt only.",
    children: [],
    findings: [],
    verdict: "No agent spend. Enable the repo under Repo Watch to enqueue.",
  },
];

Object.assign(window, {
  CHECK_OPTS,
  CONNECTORS,
  AVAILABLE,
  WATCHED_SEED,
  CONTEXTS_SEED,
  AI_STATUS,
  JOBS_SEED,
});
